---
# handlers file for cis-centos

- name: systemd restart tmp.mount
  become: yes
  systemd:
      name: tmp.mount
      daemon_reload: yes
      enabled: yes
      masked: no
      state: reloaded

- name: generate new grub config
  become: yes
  command: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: reload dconf
  become: yes
  command: dconf update

- name: restart auditd
  become: yes
  service:
      name: auditd
      state: restarted
